#!/usr/bin/env ruby

require "web_loader"
require 'web_loader/drivers/selenium_driver'
require 'optparse'


result = WebLoader::Downloader.run(ARGV)
puts result

# custom downloader example(selenium with custom wait proc)
#     wl --driver=selenium https://www.example.com
#
# class MyDownloader < WebLoader::Downloader
#   def create_wait_proc
#     #    puts "Using custom wait proc..."
#     proc do |driver|
#       # Example wait condition: wait until the document is fully loaded
#       driver.execute_script("return document.readyState") == "complete"
#     end
#   end
# end
# result = MyDownloader.run(ARGV)
# puts result